### ISSUE TITLE
OpenMP SIMD question

### ISSUE THREAD

**Issue by BradSwain** [lanl/CLAMR#69]
We are working on a static tool that flagged a potential problem with an OpenMP simd loop in CLAMR, however we are unsure if the problem we detected is real.

https://github.com/lanl/CLAMR/blob/a5f7a67419894e44f3922fdb92f396f2cead157a/l7/l7_update.c#L554-L560

Does the `offset++` line in the above loop introduce a dependency between iterations that prevents this loop from from using SIMD instructions?

I have read through the OpenMP [specification](https://www.openmp.org/spec-html/5.0/openmpsu42.html#x65-1400002.9.3.1) for simd and tried to look for some other examples, but I am still not sure how this loop would be handled.

**Comment by brobey** [comment]
So this is vectorized code rather than threaded. The directive is not quite correct. I would guess that a compiler would either detect how to handle the offset variable or refuse to vectorize it. The proper pragma should have a “linear” clause

#pragma omp simd linear(1:offset)

This is not a common case and it could very well be that some compilers would not handle it. Better coding would use the offset variable as the loop index.


From: BradSwain ***@***.***>
Reply-To: lanl/CLAMR ***@***.***>
Date: Friday, April 23, 2021 at 2:40 PM
To: lanl/CLAMR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [lanl/CLAMR] OpenMP SIMD question (#69)


We are working on a static tool that flagged a potential problem with an OpenMP simd loop in CLAMR, however we are unsure if the problem we detected is real.

https://github.com/lanl/CLAMR/blob/a5f7a67419894e44f3922fdb92f396f2cead157a/l7/l7_update.c#L554-L560

Does the offset++ line in the above loop introduce a dependency between iterations that prevents this loop from from using SIMD instructions?

I have read through the OpenMP specification<https://www.openmp.org/spec-html/5.0/openmpsu42.html#x65-1400002.9.3.1> for simd and tried to look for some other examples, but I am still not sure how this loop would be handled.

**Comment by brobey** [comment]
I changed all the pragmas for loops with an incremented offset to #pragma omp simd linear(offset:1) and Coderrect now shows it is OK -- 

Thanks, Bob! 
Those simd races are all gone
